//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace BahriaTownEnclave
{
    public partial class BillExists
    {
    }
}
